services:
  postgres:
    image: postgres:17
    container_name: rainbow-postgres
    restart: always
    environment:
      POSTGRES_DB: r-ainbow_phi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rainbow-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
